### ISSUE TITLE
Sticky keys (physical keyboard)

### ISSUE THREAD

**Issue by Cooper-Dale** [ccrisan/motionpie#168]
Known issue with bad / old driver ... please update it. ref http://elinux.org/R-Pi_Troubleshooting#Sticky_keys 
I have this problem with brand new Rpi2 and basic wire keyboard. Problem isnt detected with 2015-02-16-raspbian-wheezy or OpenELEC-RPi2.arm-5.0.7.

**Comment by ccrisan** [comment]
The firmware as well as the kernel are as up-to-date as they can be.

**Comment by fah** [comment]
I tried 3 keyboards (Microsoft, Dell, Apple) all showed:
"error opening USB device 'descriptors' file

None of the 3 keyboards worked.

Pi2B, Version 20150331

**Comment by ccrisan** [comment]
There seems to be a problem indeed with keyboards and RPI2. The weird thing is that none of the "solutions" found online makes sense for this problem. The firmware as well as the kernel are as up-to-date as they can be. The power supply that I use is good. I still experience the sticky keys and erratic behaviour with my simple Dell keyboard.

Any help regarding this issue will be appreciated.

**Comment by anjoze** [comment]
I have the same problem with RPi2 and Sticky keys.
I've made some tests:
Rpi2 + MotionPi + 3 different keyboards = Sticky keys
Rpi2 + Raspbian + 3 different keyboards = No Sticky keys
Rpi1 + MotionPi + 3 different keyboards = No Sticky keys
Rpi1 + Raspbian + 3 different keyboards = No Sticky keys
For all the tests the Power unit was the same: 5V 1200mA

**Comment by ccrisan** [comment]
Some recent commits to the RPI firmware as well as to the RPI kernel seem to do something about this issue. I'll make sure the next motionPie version uses the latest commits and let's hope for the best.

**Comment by ccrisan** [comment]
I still haven't been able to find the cause of this issue. I use the [latest Raspberry PI kernel] (https://github.com/raspberrypi/linux) and the issue is still there. Any suggestion is appreciated.

**Comment by MSumulong** [comment]
I believe this is an eudev issue: https://github.com/gentoo/eudev/issues/110, which I think should be resolved in the next buildroot release.

**Comment by ccrisan** [comment]
Does it still happen with the latest release? I remember fixing it a month or two ago.

**Comment by MSumulong** [comment]
Looking at your master branch, the package/eudev/eudev.mk shows it is using v3.0. The issue says it will be fixed for v3.1. The latest buildroot (http://git.buildroot.net/buildroot/tree/package/eudev/eudev.mk) shows its been upgraded to v3.1.1.

**Comment by ccrisan** [comment]
We're not talking about the same issue. The original problem was caused by a misconfiguration of the kernel, only for the RPi2. If the problem still persistsz it may have another cause (eudev) now.

**Comment by ccrisan** [comment]
So does the problem still happen? The eudev issue is in fact just an error message that appears in the kernel log, without affecting any functionality?

**Comment by MSumulong** [comment]
I'm not sure. I haven't been able to recreate the problem. I only have an RPi1 on hand.

**Comment by anjoze** [comment]
Hi ccrisan,
I cant test it now because I dont have my RPi with me but when possible I'll tell you if it's solved or not.
Thank you
